version: "3.5"
services:
    api_gateway:
      container_name: api_gateway
      build :
        context : .
        target: deploy 
      environment:
        localIP: jwt_service
        PORT: 8080
        consul_url: consul:8500
      ports:
        - 8080:8080
      depends_on:
        - db
        - account_service
        - jwt_service
        - upload_service
        - consul
       

    account_service:
      container_name: account_service
      #image: bwbwchen/yourgram_test
      build :
        context : ./account
        target: deploy 
      environment:
        DB_URL: db:27017
        SECRETKEY: bwbwchen
        localIP: account_service
        consul_url: consul:8500
        PORT: 12000
      expose :
        - 12000
      depends_on:
        - db
        - consul

    jwt_service:
      container_name: jwt_service
      build :
        context : ./jwt
        target: deploy 
      environment:
        SECRETKEY: bwbwchen
        localIP: jwt_service
        PORT: 12100
        consul_url: consul:8500
      expose :
        - 12100
      depends_on:
        - db
        - consul

    upload_service:
      container_name: upload_service
      build :
        context : ./upload
        target: deploy 
      environment:
        DB_URL: db:27017
        localIP: upload_service
        consul_url: consul:8500
        PORT: 12200
        minio_url: minio:9001
        minio_user: miniouser
        minio_password: minio123
      expose :
        - 12200
      depends_on:
        - db
        - consul

    consul :
      container_name : consul
      image: bitnami/consul
      expose:
        - "8500"
      ports:
        - 8501:8500

    db:
      container_name: mongodb
      image: mongo:4.0.26-xenial
      expose:
        - 27017
