version: "3"
services:
    server:
      container_name: yourgram
      image: bwbwchen/yourgram_test
      environment:
        DB_URL: db:27017
        PORT: 8080
      depends_on:
        - db
    db:
      container_name: mongodb
      image: mongo:4.0.26-xenial
      expose:
        - 27017