version: "3.5"
services:
    api_gateway:
      container_name: api_gateway
      build :
        context : .
        target: deploy 
      environment:
        IP: jwt_service
        PORT: 8080
      ports:
        - 8080:8080
      depends_on:
        - db
        - account_service
        - jwt_service
        - consul
       

    account_service:
      container_name: account_service
      #image: bwbwchen/yourgram_test
      build :
        context : ./account
        target: build 
      environment:
        DB_URL: db:27017
        SECRETKEY: bwbwchen
        IP: jwt_service
        PORT: 12000
      expose :
        - 12000
      depends_on:
        - db
        - consul

    jwt_service:
      container_name: jwt_service
      build :
        context : ./jwt
        target: build 
      environment:
        SECRETKEY: bwbwchen
        IP: jwt_service
        PORT: 12100
      expose :
        - 12100
      depends_on:
        - db
        - consul

    consul :
      container_name : consul
      image: consul:latest
      expose:
        - "8500"
      ports:
        - 8501:8500

    db:
      container_name: mongodb
      image: mongo:4.0.26-xenial
      expose:
        - 27017
