version: "3.5"
services:
    upload_service:
      container_name: upload_service
      #image: bwbwchen/yourgram_test
      build :
        context : .
        target: build 
      environment:
        DB_URL: db:27017
        localIP: upload_service
        consul_url: consul:8500
        minio_url: minio:9001
        minio_user: miniouser
        minio_password: minio123
        PORT: 12200
      expose :
        - 12200
      depends_on:
        - db
        - consul
        - minio

    consul :
      container_name : consul
      image: bitnami/consul
      expose:
        - "8500"

    minio :
      container_name : minio
      image: minio/minio
      command: server --console-address ":9001" --address ":9000" /data
      expose:
        - "9000"
        - "9001"
      environment:
        MINIO_ROOT_USER: miniouser
        MINIO_ROOT_PASSWORD: minio123

    db:
      container_name: mongodb
      image: mongo:4.0.26-xenial
      expose:
        - 27017
