// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: view_image.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ViewImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *ViewImageRequest) Reset() {
	*x = ViewImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_view_image_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewImageRequest) ProtoMessage() {}

func (x *ViewImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_view_image_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewImageRequest.ProtoReflect.Descriptor instead.
func (*ViewImageRequest) Descriptor() ([]byte, []int) {
	return file_view_image_proto_rawDescGZIP(), []int{0}
}

func (x *ViewImageRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type ViewImageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImgURLs []string `protobuf:"bytes,1,rep,name=ImgURLs,proto3" json:"ImgURLs,omitempty"`
}

func (x *ViewImageResponse) Reset() {
	*x = ViewImageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_view_image_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewImageResponse) ProtoMessage() {}

func (x *ViewImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_view_image_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewImageResponse.ProtoReflect.Descriptor instead.
func (*ViewImageResponse) Descriptor() ([]byte, []int) {
	return file_view_image_proto_rawDescGZIP(), []int{1}
}

func (x *ViewImageResponse) GetImgURLs() []string {
	if x != nil {
		return x.ImgURLs
	}
	return nil
}

var File_view_image_proto protoreflect.FileDescriptor

var file_view_image_proto_rawDesc = []byte{
	0x0a, 0x10, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x10, 0x56, 0x69, 0x65, 0x77, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x2d,
	0x0a, 0x11, 0x56, 0x69, 0x65, 0x77, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x6d, 0x67, 0x55, 0x52, 0x4c, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x49, 0x6d, 0x67, 0x55, 0x52, 0x4c, 0x73, 0x32, 0x45, 0x0a,
	0x10, 0x56, 0x69, 0x65, 0x77, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x31, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x11, 0x2e,
	0x56, 0x69, 0x65, 0x77, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_view_image_proto_rawDescOnce sync.Once
	file_view_image_proto_rawDescData = file_view_image_proto_rawDesc
)

func file_view_image_proto_rawDescGZIP() []byte {
	file_view_image_proto_rawDescOnce.Do(func() {
		file_view_image_proto_rawDescData = protoimpl.X.CompressGZIP(file_view_image_proto_rawDescData)
	})
	return file_view_image_proto_rawDescData
}

var file_view_image_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_view_image_proto_goTypes = []interface{}{
	(*ViewImageRequest)(nil),  // 0: ViewImageRequest
	(*ViewImageResponse)(nil), // 1: ViewImageResponse
}
var file_view_image_proto_depIdxs = []int32{
	0, // 0: ViewImageService.GetImage:input_type -> ViewImageRequest
	1, // 1: ViewImageService.GetImage:output_type -> ViewImageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_view_image_proto_init() }
func file_view_image_proto_init() {
	if File_view_image_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_view_image_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_view_image_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewImageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_view_image_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_view_image_proto_goTypes,
		DependencyIndexes: file_view_image_proto_depIdxs,
		MessageInfos:      file_view_image_proto_msgTypes,
	}.Build()
	File_view_image_proto = out.File
	file_view_image_proto_rawDesc = nil
	file_view_image_proto_goTypes = nil
	file_view_image_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ViewImageServiceClient is the client API for ViewImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ViewImageServiceClient interface {
	GetImage(ctx context.Context, in *ViewImageRequest, opts ...grpc.CallOption) (*ViewImageResponse, error)
}

type viewImageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewViewImageServiceClient(cc grpc.ClientConnInterface) ViewImageServiceClient {
	return &viewImageServiceClient{cc}
}

func (c *viewImageServiceClient) GetImage(ctx context.Context, in *ViewImageRequest, opts ...grpc.CallOption) (*ViewImageResponse, error) {
	out := new(ViewImageResponse)
	err := c.cc.Invoke(ctx, "/ViewImageService/GetImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ViewImageServiceServer is the server API for ViewImageService service.
type ViewImageServiceServer interface {
	GetImage(context.Context, *ViewImageRequest) (*ViewImageResponse, error)
}

// UnimplementedViewImageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedViewImageServiceServer struct {
}

func (*UnimplementedViewImageServiceServer) GetImage(context.Context, *ViewImageRequest) (*ViewImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImage not implemented")
}

func RegisterViewImageServiceServer(s *grpc.Server, srv ViewImageServiceServer) {
	s.RegisterService(&_ViewImageService_serviceDesc, srv)
}

func _ViewImageService_GetImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewImageServiceServer).GetImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ViewImageService/GetImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewImageServiceServer).GetImage(ctx, req.(*ViewImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ViewImageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ViewImageService",
	HandlerType: (*ViewImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetImage",
			Handler:    _ViewImageService_GetImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "view_image.proto",
}
